### ISSUE TITLE
Window pane borders

### ISSUE THREAD

**Issue by gngrossi** [zopencommunity/tmuxport#10]
Will border characters be solid lines?

**Panes**
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/de62185e-b36a-4737-a351-1c268526ae27)

**Window list**
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/edb4b4ec-1e8a-4dac-a99c-02d7ea3eeee1)

**Session list**
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/f004aac3-3d8e-4cf5-b9c6-88dbd5204f13)

**Comment by gngrossi** [comment]
man tmux difference using PuTTY

**Outside tmux**
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/c52c237e-27d8-48da-93a4-852fdd1dba42)

**Inside tmux**
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/45a9bfc1-3404-4b75-af27-91341b6f9702)

**Comment by gngrossi** [comment]
Interesting...trying to determine the difference between PuTTY and the Windows OS OpenSSH client

PuTTY
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/a4dda31a-f6ac-44f3-b417-f917992e36bb)

Windows OpenSSH
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/13b3cfb2-5d29-4fa8-92d8-fc1534c173a9)

**Comment by IgorTodorovskiIBM** [comment]
Interesting, It could be the fonts, I am using iTerm2 on Mac and I see the solid borders.

It seems like for `man tmux` to display correctly, you need to run tmux in utf8 mode.

`tmux -u` - that's when I see the C-b rendered correctly

**Comment by gngrossi** [comment]
After upgrading tmux, using tmux -u, with /bin/sh, sourcing zopen-config with exec bash:
- the pane borders are solid lines
- the Window and Session lists are solid lines with the expected tree characters
- after set -g mouse on, the menu pop-up looks good

All good!

Very minor but...for man tmux:

**Without utf8 (tmux)**
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/a80ba68e-6c5a-4008-a156-26be9becf163)
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/800f7073-e606-4cc7-b586-01df433cf310)

**With utf8 (tmux -u)**
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/147a974d-63b4-4e99-b375-05b191a9b983)
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/6d7c4313-ca41-4c2f-aab3-41d9a3b5ce8a)

thanks again

**Comment by gngrossi** [comment]
I forgot to include the PuTTY configuration
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/445254a1-89d2-4ddd-9c1e-06643a60ef1b)

**Comment by gngrossi** [comment]
With PuTTY, using an alias to resolve...closing.

alias tmux='export TERM=xterm-256color && tmux -u'
