### ISSUE TITLE
FSUM9209 cannot execute: reason code = 02550199: EDC5137I Inappropriate I/O control operation

### ISSUE THREAD

**Issue by gngrossi** [zopencommunity/tmuxport#3]
# without a $HOME/.tmux.conf file or without set-option -g default-shell $ZOPEN_PKGINSTALL/bash/bash/bin/bash

Is this expected?

bash-5.2$ tmux
grep: /u/@02858/.profile 81: FSUM9209 cannot execute: reason code = 02550199: EDC5137I Inappropriate I/O control operation. (errno2=0x02550199)
awk: /u/@02858/.profile 81: FSUM9209 cannot execute: reason code = 02550199: EDC5137I Inappropriate I/O control operation. (errno2=0x02550199)
df: /u/@02858/.profile 81: FSUM9209 cannot execute: reason code = 02550199: EDC5137I Inappropriate I/O control operation. (errno2=0x02550199)
grep: /u/@02858/.profile 81: FSUM9209 cannot execute: reason code = 02550199: EDC5137I Inappropriate I/O control operation. (errno2=0x02550199)
awk: /u/@02858/.profile 81: FSUM9209 cannot execute: reason code = 02550199: EDC5137I Inappropriate I/O control operation. (errno2=0x02550199)
df: /u/@02858/.profile 81: FSUM9209 cannot execute: reason code = 02550199: EDC5137I Inappropriate I/O control operation. (errno2=0x02550199)

**Comment by IgorTodorovskiIBM** [comment]
Thanks for opening up the issue. Yep, the only way it works at the moment is via bash

**Comment by gngrossi** [comment]
Closing...

**Comment by IgorTodorovskiIBM** [comment]
I'll reopen since it's a legitimate issue. I want to fix it at some point

**Comment by IgorTodorovskiIBM** [comment]
This should be fixed with the latest version

**Comment by gngrossi** [comment]
After upgrading, now working with /bin/sh
Excellent...well done, thanks

~/.tmux.conf
set -g default-shell $SHELL

closing...
