### ISSUE TITLE
Unexpected profile sourcing

### ISSUE THREAD

**Issue by gngrossi** [zopencommunity/tmuxport#4]
Is this expected? Any way to avoid it?

Using your supplied .tmux.conf (very helpful and thanks)
from a bash shell and running tmux:
- sources /etc/profile (declare -x for each environment variable)
- sources .profile
- sources .bashrc

![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/1a2bc1a7-e40a-40d8-a556-6fd3d80016a2)

**Comment by gngrossi** [comment]
Without tmux, and in an interactive bash shell, running bash again will source .bashrc as expected.
bash-5.2$ bash
hello from ~/.bashrc

After exiting, running bash --login will source /etc/profile, .profile and .bashrc

Should starting a tmux session (and creating a window in the session), run bash or bash --login?

**Comment by gngrossi** [comment]
After starting a new tmux session, here's the PATH from the window. This isn't what I expect after sourcing /etc/profile, .profile and .bashrc ?
The PS1 prompt looks like bash 5.2 is available but it's not. The zopen tools are not in the PATH.  
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/4edf8580-521b-48dd-8493-fb7f3a478367)

Here's my PATH from a system using a /bin/sh session without sourcing zopen tools.
/usr/lpp/java/J11.0_64/bin:/usr/lpp/java/J8.0_64/bin:/bin:.:/hewitt/coz/current/bin:/usr/local/bin:/usr/local/sbin:/usr/lpp/ported/bin:/usr/sbin:/usr/lpp/NFS:/u/@02858/scripts

**Comment by gngrossi** [comment]
Correction...it is not sourcing $HOME/.profile

**Comment by IgorTodorovskiIBM** [comment]
Another way to invoke tmux with bash is via:
```
SHELL=/home/itodoro/zopen/usr/local/bin/bash tmux
```
This is different in that it will inherit the environment variables from the parent.

**Comment by gngrossi** [comment]
Workaround...
Using set -g default-shell $SHELL in ~/.tmux.conf
Seeing the /bin/sh FSUM9209 messages but the sourcing looks good, /etc/profile and ~/.profile
I then source zopen-config and exec bash to run the zopen tools.
![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/47efe72c-9743-4402-94a9-fad614abfef4)

My tmux session window is bash...all good.
Same process (/bin/sh, zopen-config, exec bash) running tmux as I do without.

Thoughts?
thanks

**Comment by gngrossi** [comment]
After upgrading, now working with /bin/sh (sourcing /etc/profile and ~/.profile as expected).
Updated and closed this issue as well.  https://github.com/ZOSOpenTools/tmuxport/issues/3

closing...
