### ISSUE TITLE
README article 404

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zopencommunity/tmuxport#5]
Readme says to go to https://igortodorovskiibm.github.io/blog/2024/03/08/tmux/ but it doesn't exist.

**Comment by IgorTodorovskiIBM** [comment]
Ah I changed the date, will update it. It's https://igortodorovskiibm.github.io/blog/2024/03/12/tmux/

**Comment by 1000TurquoisePogs** [comment]
Great thanks!
