### ISSUE TITLE
clear: FSUM Unknown terminal

### ISSUE THREAD

**Issue by gngrossi** [zopencommunity/tmuxport#6]
clear command results in an error using xterm-256color

![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/8779daea-0560-4116-b9f0-c4c56ff047a1)

After export TERM=xterm, clear works as expected.

**Comment by gngrossi** [comment]
Using TERM=xterm does work with colors without and with tmux

![image](https://github.com/ZOSOpenTools/tmuxport/assets/115715798/896690a2-19b2-48ad-b615-f4be25fec507)

**Comment by gngrossi** [comment]
Updated $HOME/.tmux.conf

#set -g default-terminal "xterm-256color"
set -g default-terminal "xterm"

Is this a permanent solution?
thanks

**Comment by IgorTodorovskiIBM** [comment]
If you install ncurses, it provides a version of clear that works with xterm-256color. This issue is happening because the z/OS TERMINFO doesn't provide an xterm-256color, but the ncurses db does.

```
ls /usr/share/lib/terminfo/x/
```

vs

```
ls $ZOPEN_PKGINSTALL/ncurses/ncurses-6.4/share/terminfo/x
```

**Comment by gngrossi** [comment]
Sorry for the confusion. I do have ncurses 6.4 installed.
Here's what occurs which I have subsequently determined:
Before using tmux, I SSH to z/OS with my default shell /bin/sh (RACF segment) and then source zopen-config and exec bash.
This is my starting point for running all zopen tools.

I run tmux using set -g default-shell $ZOPEN_PKGINSTALL/bash/bash/bin/bash in ~/.tmux.conf
From the terminal messages, sourcing looks to be /etc/profile, ~/.profile and ~/.bashrc. but it doesn't appear my .profile ran successfully after echoing $PATH, etc. The SHELL prompt (PS1) is proper being set in .bashrc.

In a tmux session window, I assumed I was sourced to the zopen tools which isn't the case.

Closing this issue and will update https://github.com/ZOSOpenTools/tmuxport/issues/4 for the workaround.
thanks

**Comment by gngrossi** [comment]
Closing...
