### ISSUE TITLE
connect failed: EDC8128I Connection refused. (errno2=0x120D0253)

### ISSUE THREAD

**Issue by gngrossi** [zopencommunity/tmuxport#7]
Not sure if this is an issue.

tmux -v

tmux-client-67834113.log

14:48:12 RC=(0) [SYSA] bash-5.2$ head -n25 tmux-client-67834113.log
1710445514.695529 client started (67834113): version 3.3a, socket /SYSA/tmp/tmux-2858/default, protocol 8
1710445514.695573 on OS/390 28.00 04
1710445514.695579 using libevent 2.1.12-stable (poll); ncurses 6.4
1710445514.695590 flags are 0x18000000
1710445514.695595 socket is /SYSA/tmp/tmux-2858/default
**1710445514.695610 trying connect
1710445514.695672 connect failed: EDC8128I Connection refused. (errno2=0x120D0253)**
1710445514.695694 lock file is /SYSA/tmp/tmux-2858/default.lock
1710445514.695783 flock succeeded
1710445514.695788 got lock (6)
**1710445514.695795 trying connect
1710445514.695836 connect failed: EDC8128I Connection refused. (errno2=0x120D0253)**
1710445514.709970 add peer 5008A0DEF0: 7 (0)
1710445514.710995 sending message 100 to peer 5008A0DEF0 (4 bytes)
1710445514.711007 sending message 111 to peer 5008A0DEF0 (8 bytes)
1710445514.711037 sending message 101 to peer 5008A0DEF0 (6 bytes)
1710445514.711043 sending message 109 to peer 5008A0DEF0 (4 bytes)
1710445514.711048 sending message 102 to peer 5008A0DEF0 (14 bytes)
1710445514.711054 sending message 108 to peer 5008A0DEF0 (10 bytes)
1710445514.711059 sending message 112 to peer 5008A0DEF0 (58 bytes)
1710445514.711064 sending message 112 to peer 5008A0DEF0 (5 bytes)
1710445514.711069 sending message 112 to peer 5008A0DEF0 (5 bytes)
1710445514.711074 sending message 112 to peer 5008A0DEF0 (6 bytes)
1710445514.711080 sending message 112 to peer 5008A0DEF0 (6 bytes)
1710445514.711085 sending message 112 to peer 5008A0DEF0 (11 bytes)

**Comment by IgorTodorovskiIBM** [comment]
I'm seeing this on my Mac with tmux as well:
```
1710791967.646231 client started (89784): version 3.4, socket /private/tmp/tmux-501/default, protocol 8
1710791967.646298 on Darwin 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64
1710791967.646319 using libevent 2.1.12-stable select
1710791967.646334 using utf8proc 2.9.0
1710791967.646342 using ncurses 6.4 20221231
1710791967.646376 flags are 0x18010000
1710791967.646386 socket is /private/tmp/tmux-501/default
1710791967.646400 trying connect
1710791967.646420 connect failed: Connection refused
1710791967.646441 lock file is /private/tmp/tmux-501/default.lock
1710791967.646552 flock succeeded
1710791967.646570 got lock (6)
1710791967.646582 trying connect
1710791967.646597 connect failed: Connection refused
1710791967.647493 add peer 0x7ff5d0008000: 7 (0x0)
```

**Comment by gngrossi** [comment]
ok...closing
