### ISSUE TITLE
tmux processes

### ISSUE THREAD

**Issue by gngrossi** [zopencommunity/tmuxport#9]
Is this expected?
running tmux 3.3a

**tmux processes:**
- 1 tmux server process
- 5 /bin/sh processes (one for each window pane...3 windows...5 panes)

bash-5.2$ ps -ef
     UID        PID       PPID  C    STIME TTY       TIME CMD
  @02858   34278152                1  - 12:38:20 ?         0:01 tmux
  @02858   51058302   34278152  - 12:38:20 ?         0:00 -sh
  @02858   67831427   34278152  - 12:38:42 ?         0:00 -sh
  @02858   17501394   34278152  - 12:38:46 ?         0:00 -sh
  @02858   17501970   34278152  - 12:38:48 ?         0:00 -sh
  @02858   67834048   34278152  - 12:38:56 ?         0:00 -sh

**Comment by IgorTodorovskiIBM** [comment]
Yep, the tmux service runs in the background and each pane is a child process. The same thing can be seen on linux as well.

**Comment by gngrossi** [comment]
Closing...
